# config:
#   modules:
#     http_2xx:
#       prober: http
#       timeout: 15s
#       http:
#         valid_status_codes: [200, 201, 202, 203, 204, 205, 206, 207, 208, 226, 401, 405]
#         valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
#         follow_redirects: true
#         preferred_ip_protocol: "ip4"